# Generated by Django 3.2.5 on 2021-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profile_pics/default_avatar.jpg', upload_to='profile_pics'),
        ),
    ]
