# Generated by Django 3.2.5 on 2021-07-24 06:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_pics/default_avatar.jpg', force_format='JPG', keep_meta=True, quality=75, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
