# Generated by Django 3.2.5 on 2021-07-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='banner_pics/default_banner.jpg', upload_to='banner_pics'),
        ),
    ]
