# Generated by Django 3.2.5 on 2021-07-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner',
            new_name='img_url',
        ),
    ]
