# Generated by Django 3.2.5 on 2021-07-24 06:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, default='banner_pics/default_banner.jpg', force_format='JPG', keep_meta=True, quality=90, size=[600, 400], upload_to='banner_pics'),
        ),
    ]
