# Generated by Django 3.2.5 on 2021-07-28 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blogviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogViews',
            new_name='BlogView',
        ),
    ]
